### PR TITLE
Use Scan to Build and use released version of Quick

### PR DESCRIPTION
**Pull request by rajatvig**
I created a [post](https://medium.com/@rajatvig/ios-docker-and-consumer-driven-contract-testing-with-pact-d99b6bf4b09e#.ozcbbktzk) on how to use it and was planning to update it to use Swift 3.
Is there a release timeline around this branch?

### CODE REVIEW

**Comment by mefellows** [comment]
Nice work on that post @rajatvig!

**Comment by andrewspinks** [comment]
@rajatvig I was waiting for the dependencies to be updated to swift 3. It looks like that has now been done, so I'll look at merging this in and releasing it tomorrow. Thanks for the writeup!!

**Comment by rajatvig** [comment]
@mefellows @andrewspinks thanks for the praise. 
will watch for the release and update it.

Would it be fine to refer to the post in the ReadMe?

**Comment by andrewspinks** [comment]
@rajatvig Yep, that is fine.

**Comment by rajatvig** [comment]
@andrewspinks should I update this PR or create a new one?

**Comment by andrewspinks** [comment]
@rajatvig Just update this one if you want

**Pull request merged**
