### PR TITLE
Update to latest version of Almofire

### PR DESCRIPTION
**Pull request by richardPFisk**
Could we update to the latest version of Almofire?

### CODE REVIEW

**Comment by richardPFisk** [comment]
Please bear with me whilst I ensure the builds pass.

**Comment by andrewspinks** [comment]
@richardPFisk I have had a lot of problems trying to get CI builds to work due to code signing issues (which is why I never got around to merging these changes back into master). Maybe with the XCode 7.2 it has magically started working again, but I haven't looked.

**Comment by richardPFisk** [comment]
@andrewspinks, I have been having similar problems. It seems a shame to be held up by the signing identity. The script outlined [here](https://github.com/travis-ci/travis-ci/issues/3072) did not look to complicated as long as there exists a dev certificate somebody is happy to use.

How would you like to proceed?

**Comment by andrewspinks** [comment]
@richardPFisk agreed - however, I think I have spent more time fixing code signing issues on this project than writing code (It seems to break every XCode version) which is pretty demotivating.

I can have a look at the solutions in that github issue, but it might take me a few days to get around to it.

There are a few other options that I have been considering as well:
- ditching carthage and building using cocoapods (this would require all clients to use cocoapods though, which I am not a fan of). 
- removing extra dependencies (BrightFutures). I often only get code signing issues with one of the dependencies, so reducing them might stabilise the build.

**Comment by andrewspinks** [comment]
@richardPFisk So I tried going back a few commits to when I was building with a certificate and it seems to be compiling now on XCode 7.2 (or maybe travisci fixed something?). Tests didn't run for some reason, but I'll have to investigate that later. I'll take a look at your pull request once I get the build working again.

**Comment by richardPFisk** [comment]
Good work @andrewspinks! 

I tested your theory of whether fixed something by kicking off a known commit that fails due to certificates and it seems just fails in the same way. This suggests to me that there _is_ some code/project difference.

**Comment by andrewspinks** [comment]
@richardPFisk I manually merged your changes. I bumped the version to 0.1.5

**Pull request closed without merging**
